name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Run linters
        run: |
          make lint

      - name: Run formatters
        run: |
          sudo snap install yq
          make format

      - name: Check for modifications to generated files
        run: |
          if [[ -n "$(git status -s)" ]]; then
            echo "Please run 'make format' then commit/push changes"
            echo
            git diff
            exit 1
          fi
